#!/usr/bin/python
"""Generate random passwords

.. sectionauthor:: Asher Bender <a.bender.dev@gmail.com>
.. codeauthor:: Asher Bender <a.bender.dev@gmail.com>

"""

#    Copyright (C) 2015, Asher Bender
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import time
import math
import string
import argparse
import textwrap
import subprocess

# Default password length.
DEFAULT_LENGTH = 24

# Set of characters available for use in passwords.
CHARS = string.ascii_uppercase + string.ascii_lowercase + \
        string.digits + string.punctuation


def permutations(N, L):
    """Calculate the number of password permutations.

    Args:
        N (int): number of symbols (character choices).
        L (int): length of password.

    Returns:
        int: number of password permutations.

    """

    return N**L


def information_entropy(N):
    """Calculate the information entropy per symbol for a truly random password.

    Args:
        N (int): number of symbols (character choices).

    Returns:
        float: information entropy per symbol in bits.

    """

    return math.log(N) / math.log(2)


def summary(N, L):
    """Summarise information for a truly random password.

    Produce a summary of a password in the form:

        Number of symbols:  <int>
        Password length:    <int>
        Permutations:       <int>
        Entropy per symbol: <float> bits
        Total entropy:      <float> bits

    Args:
        N (int): number of symbols (character choices).
        L (int): length of password.

    Returns:
        string: summary of password information.

    """

    # Calculate information entropy.
    H = information_entropy(N)
    eps = '%1.3f bits' % H
    te = '%1.3f bits' % (H * L)
    length = max(len(eps), len(te))

    # Use integer notation if 'small', use exponential notation if 'large'
    P = permutations(N, L)
    if P < 1000000:
        per = '{0:,g}'.format(P)
    else:
        P
        per = '10^%i' % math.log10(P)

    # Create summary string.
    S  = 'Number of symbols:  %i\n' % N
    S += 'Password length:    %i\n' % L
    S += 'Permutations:       %s\n' % per
    S += 'Entropy per symbol: %s\n' % eps.rjust(length, ' ')
    S += 'Total entropy:      %s\n' % te.rjust(length, ' ')

    return S


def check_entropy():
    """Return the amount of entropy available to the system.

    Read the amount of entropy available to the system from

        /proc/sys/kernel/random/entropy_avail

    The read-only file entropy_avail gives the available entropy. Normally,
    this will be 4096 (bits), a full entropy pool.

    Returns:
        int: entropy available to the system in bits.

    """

    cmd = ['cat', '/proc/sys/kernel/random/entropy_avail']
    entropy = subprocess.check_output(cmd)
    return int(entropy)


def byte_to_char(byte, chars):
    """Convert a byte to a character.

    Args:
        byte (uint8): byte.
        characters (list): the list of characters ``byte`` can be mapped onto.

    Returns:
        str: character

    """

    # Convert byte to a location in the input character list.
    if byte < 255:
        index = int(len(chars) * (float(byte) / 255.))

    # Note that when byte==255, 'index' will be equal to len(chars). All other
    # values for 'byte' will be cast to an integer value less than
    # len(char). To handle this boundary case, return the index of the final
    # character.
    elif byte == 255:
        index = len(chars) - 1

    # Input is not a true byte.
    elif byte > 255:
        Exception('Expected a uint8')

    return chars[index]


def generate_password(length, pool_reserve=128, characters=CHARS, verbose=True):
    """Generate a random password by drawing bytes from /dev/random.

    Args:
        length (int): Length of the random password in characters.
        pool_reserve (int, **optional**): Only sample a byte from /dev/random
            when the entropy available to the system is higher than
            ``pool_reserve``.
        characters (list, **optional**): list of characters available for
            generating elements of password.

    Returns:
        str: a randomly generated password.

    """

    # Define stdout message format.
    msg = 'Entropy available: %04d bits,  Characters sampled: %i\r'

    j = 0
    password = list()
    start_time = time.time()
    with open("/dev/random", 'rb') as f:

        # Read one byte from /dev/random. This will deplete entropy available
        # to the system and force the algorithm to wait for the pool reserve to
        # grow.
        f.read(1)

        # Sample bytes from /dev/random.
        while j < length:
            entropy = check_entropy()

            # If there is enough entropy in the pool, draw a random byte from
            # /dev/random.
            if entropy > pool_reserve:
                password.append(byte_to_char(ord(f.read(1)), characters))
                j += 1

            # Sleep for a short period.
            end_time = time.time()
            if end_time - start_time > 1:
                start_time = end_time
                if verbose:
                    sys.stdout.write(msg % (entropy, j))
                    sys.stdout.flush()
            else:
                time.sleep(0.25)

    if verbose:
        sys.stdout.write((msg % (entropy, j))[:-1] + '\n')

    return str(''.join(password))


if __name__ == '__main__':

    # Can only operate on systems with /dev/random.
    if not os.path.exists('/dev/random'):
        raise IOError("Could not locate '/dev/random'. Cannot run pwdgen.")

    # -------------------------------------------------------------------------
    #         Configure command-line options & parsing behaviour
    # -------------------------------------------------------------------------

    man = """Generate random passwords."""
    formatter_class = argparse.RawDescriptionHelpFormatter
    parser = argparse.ArgumentParser(formatter_class=formatter_class,
                                     description=textwrap.dedent(man))

    parser.add_argument('-L', '--length', metavar='<int>', type=int,
                        default=DEFAULT_LENGTH,
                        help='length of password (default=%i)' % DEFAULT_LENGTH)

    msg = "Exclude uppercase letters:  %s" % string.ascii_uppercase
    parser.add_argument('-u', '--upper', action='store_false', default=True,
                        help=msg)

    msg = "Exclude lowercase letters:  %s" % string.ascii_lowercase
    parser.add_argument('-l', '--lower', action='store_false', default=True,
                        help=msg)

    msg = "Exclude numeric characters: %s" % string.digits
    parser.add_argument('-n', '--numeric', action='store_false', default=True,
                        help=msg)

    msg = "Include punctuation characters: %s" % string.punctuation
    msg = msg.replace('%', '%%')
    parser.add_argument('-p', '--punctuation', action='store_true',
                        default=False, help=msg)

    msg = "Specify which characters will be used for random password "
    msg += "generation (--upper, --lower, --numeric and --punctuation)."
    parser.add_argument('--include', metavar='<string>', default=None, help=msg)

    msg = "Specify which characters will be excluded from random password "
    msg += "generation."
    parser.add_argument('--exclude', metavar='<string>', default=None, help=msg)

    msg = "Print characters available for random password generation and exit."
    parser.add_argument('--list', action='store_true', default=False, help=msg)

    parser.add_argument('-q', '--quiet', action='store_true', default=False,
                        help="Surpress output to stdout.")

    # Get arguments from the command-line.
    args = parser.parse_args()

    # -------------------------------------------------------------------------
    #                  Create list of available characters
    # -------------------------------------------------------------------------

    # Use default characters.
    if args.include is None:
        characters = ''

        # Exclude uppercase letters.
        if args.upper:
            characters += string.ascii_uppercase

        # Exclude lowercase letters.
        if args.lower:
            characters += string.ascii_lowercase

        # Exclude numeric characters.
        if args.numeric:
            characters += string.digits

        # Include punctuation characters.
        if args.punctuation:
            characters += string.punctuation

    # Use input characters.
    else:
        characters = ''.join(set(args.include))

    # Exclude user specified characters.
    if args.exclude is not None:
        characters = ''.join(set(characters) - set(args.exclude))

    # No characters are available. Exit.
    if not characters:
        print "Character set is empty. Cannot generate random passwords."
        sys.exit()

    # Ensure characters is a unique and sorted string.
    characters = ''.join(sorted(set(characters)))

    # Print available characters and exit.
    if args.list:
        print characters
        sys.exit()

    # -------------------------------------------------------------------------
    #                       Generate random password
    # -------------------------------------------------------------------------
    N = len(characters)
    L = args.length

    if not args.quiet:
        print summary(N, L)

        msg = """Collecting environmental noise collected from device drivers and other
              sources. It is a good idea to perform some other action (type on the
              keyboard, move the mouse, utilize the disks) during the prime
              generation; this gives the random number generator a better chance to
              gain enough entropy."""
        print textwrap.fill(msg, width=70) + '\n'

    password = generate_password(L, characters=characters,
                                 verbose=not args.quiet)

    if not args.quiet:
        print

    print password
